config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  scope '(:locale)', locale: /en|es|ca/ do
    root "pages#home"
    get 'business', to: 'pages#business', as: 'business'
    get 'services', to: 'pages#services', as: 'services'
    get 'trajectory', to: 'pages#trajectory', as: 'trajectory'
    get 'contact', to: 'contact#new', as: 'contact'
    post 'contact', to: 'contact#create'
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :set_locale

  def set_locale
    I18n.locale = params[:locale] || I18n.default_locale
  end
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
  def new; end
  def create; end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home; end

  def business; end

  def services; end

  def trajectory; end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def nav_link_class(path)
    'nav-link' + (' active' if current_page?(path)).to_s
  end

  def nav_lang_class(locale)
    'nav-link nav-lang' + (' active' if I18n.locale == locale).to_s
  end
end

app/views/contact/new.html.erb
<script src="https://www.google.com/recaptcha/enterprise.js" async defer></script>

<div class="container contact-page">
  <h1 class="title"><%= t('contact.title') %></h1>
  <p class="description"><%= t('contact.description') %></p>

  <%= render 'shared/contact_data', white_logos: false %>

  
  <%= form_with(url: '/cgi-bin/send_contact.py', method: :post, class: 'row g-3 form-contact') do |form| %>
    <div class="col-md-6">
      <%= form.label :name, t('contact.form.name'), class: 'form-label' %>
      <%= form.text_field :name, class: 'form-control', required: true %>
    </div>

    <div class="col-md-6">
      <%= form.label :email, t('contact.form.email'), class: 'form-label' %>
      <%= form.email_field :email, class: 'form-control', required: true %>
    </div>

    <div class="col-md-6">
      <%= form.label :mobile_number, t('contact.form.mobile_number'), class: 'form-label' %>
      <%= form.telephone_field :mobile_number, class: 'form-control', required: true %>
    </div>

    <div class="col-12">
      <%= form.label :message, t('contact.form.message'), class: 'form-label' %>
      <%= form.text_area :message, class: 'form-control', rows: 4, required: true %>
    </div>

    <div class="g-recaptcha" data-sitekey="<%= ENV['RECAPTCHA_SITE_KEY'] %>" data-action="contact"></div>

    <div class="col-12">
      <%= form.submit t('btn.send'), class: 'btn btn-primary' %>
    </div>
  <% end %>
</div>

app/views/layouts/_footer.html.erb
<footer>
  <div class="row text-center">
    <div class="col">
      <%= image_tag("logo-grey.svg", alt: "Logo", class: "img-fluid logo-menu") %>
    </div>
  </div>
  
  <%= render 'shared/contact_data', white_logos: true %>
  
  <div class="row row-contact-info text-center">
    <div class="col-sm-12 col-md-6 ">
      <%= image_tag("ESPOS_footer_mini.png", alt: "Logo NextGenerationEU", class: "img-fluid logo-eu") %>
    </div>
    <div class="col-sm-12 col-md-6 mt-3 mt-md-0">
      <%= image_tag("PRTR_footer_mini.png", alt: "Logo NextGenerationEU", class: "img-fluid logo-eu") %>
    </div>
  </div>

  <hr>

  <div class="row text-center mt-3">
    <div class="col">
      Constructora d'obres i serveis del Baix Camp S. L.
    </div>
  </div>  
</footer>

app/views/layouts/_menu.html.erb
<nav class="navbar navbar-expand-lg bg-light">
  <div class="container-fluid">
    <%= link_to(root_path, class: 'navbar-brand') do %>
      <%= image_tag("logo.png", alt: "Logo", class: "logo-menu") %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>    

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <hr class="d-lg-none">
      <ul class="navbar-nav mb-2 mb-lg-0">
        <li class="nav-item nav-page">
          <%= link_to(t('menu.home'), root_path, class: nav_link_class(root_path)) %>
        </li>
        <li class="nav-item nav-page">
          <%= link_to(t('menu.business'), business_path, class: nav_link_class(business_path)) %>
        </li>
        <li class="nav-item nav-page">
          <%= link_to(t('menu.services'), services_path, class: nav_link_class(services_path)) %>
        </li>
        <li class="nav-item nav-page">
          <%= link_to(t('menu.trajectory'), trajectory_path, class: nav_link_class(trajectory_path)) %>
        </li>
        <li class="nav-item nav-page">
          <%= link_to(t('menu.contact'), contact_path, class: nav_link_class(contact_path)) %>
        </li>
        <hr class="d-lg-none">
        <li class="nav-item d-lg-none">
            <%= link_to("Cat", url_for(locale: :ca), class: nav_lang_class(:ca)) %>
            <%= link_to("Es", url_for(locale: :es), class: nav_lang_class(:es)) %>
            <%= link_to("En", url_for(locale: :en), class: nav_lang_class(:en)) %>
        </li>
      </ul>
    </div>

    <div class="navbar-nav float-end d-none d-lg-block">
      <div class="nav-item">
        <%= link_to("Cat", url_for(locale: :ca), class: nav_lang_class(:ca)) %>
      </div>
      <div class="nav-item">
        <%= link_to("Es", url_for(locale: :es), class: nav_lang_class(:es)) %>
      </div>
      <div class="nav-item">
        <%= link_to("En", url_for(locale: :en), class: nav_lang_class(:en)) %>
      </div>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="<%= I18n.locale %>">
  <head>
    <title><%= t("header.title") %></title>
    <meta charset="UTF-8">
    <meta name="description" content="<%= t("header.description") %>">
    <meta name="keywords" content="<%= t("header.keywords") %>">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.0/css/all.min.css" rel="stylesheet">
  </head>

  <body>
    <%= render 'layouts/menu' %>
    <%= yield %>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/pages/business.html.erb
<div class="container business-page">
  <h1 class="title"><%= t('business.title') %></h1>
  <p class="description"><%= t('business.description_1') %></p>
  <p class="description"><%= t('business.description_2') %></p>

  <h1 class="title"><%= t('business.title_our_values') %></h1>
  <div class="row widgets-value">
    <% 6.times do |i| %>
      <div class="col-sm-12 col-md-6 col-lg-4 widget-col">
        <div class="widget-value">
          <div class="widget-content">
            <%= image_tag('robotic-arm.svg', class: 'widget-icon') %>
            <h1 class="widget-title"><%= t("business.widget_values.widget_#{i+1}.title") %></h1>
          </div>
        </div>
      </div>
    <% end %>
  </div>

  <%= render 'shared/carousel', location: 'carousel/business', n_items: 5%>
</div>

app/views/pages/home.html.erb
<%= render 'shared/carousel', location: 'carousel/home', n_items: 6 %>

<div class="container home-page">
  <h1 class="title"><%= t('home.title') %></h1>
  <p class="description"><%= t('home.description') %></p>

  <div class="redirections">
    <div class="widgets-container row">
      <div class="col-sm-12 col-md-6">
        <div class="widget-container">
          <%= image_tag("business.png", alt: "", class: "img-fluid widget-image") %>
          <div class="widget-title"><%= t('home.redirections.business.title') %></div>
          <div class="widget-description"><%= t('home.redirections.business.description') %></div>
          <%= link_to(business_path, class: 'widget-button') do %>
            <%= t('btn.know_more') %>
            <i class="fas fa-arrow-right"></i>
          <% end %>
        </div>
      </div>

      <div class="col-sm-12 col-md-6">
        <div class="widget-container">
          <%= image_tag("serveis.png", alt: "", class: "img-fluid widget-image") %>
          <div class="widget-title"><%= t('home.redirections.services.title') %></div>
          <div class="widget-description"><%= t('home.redirections.services.description') %></div>
          <%= link_to(services_path, class: 'widget-button') do %>
            <%= t('btn.know_more') %>
            <i class="fas fa-arrow-right"></i>
          <% end %>
        </div>
      </div>
    </div>
  </div>

  <div class="contact">
    <h1 class="contact-title"><%= I18n.t('home.contact.title') %></h1>
    <p class="contact-description"><%= I18n.t('home.contact.description') %></p>
    <%= link_to(contact_path, class: 'contact-button') do %>
      <%= t('btn.contact') %>
    <% end %>
  </div>
</div>

app/views/pages/services.html.erb
<%= render 'shared/carousel', location: 'carousel/services', n_items: 5 %>

<div class="container services-page">
  <h1 class="title"><%= t('services.new_construction.title') %></h1>
  <p class="description"><%= t('services.new_construction.description') %></p>
  <%= render 'shared/carousel', location: 'carousel/services/new_construction', n_items: 13 %>
  <%= link_to(contact_path, class: 'info-button') do %>
    <%= t('btn.ask-info') %>
  <% end %>


  <h1 class="title"><%= t('services.renovation.title') %></h1>
  <p class="description"><%= t('services.renovation.description') %></p>
  <%= render 'shared/carousel', location: 'carousel/services/renovation', n_items: 5 %>
  <%= link_to(contact_path, class: 'info-button') do %>
    <%= t('btn.ask-info') %>
  <% end %>

  <h1 class="title"><%= t('services.rehabilitation.title') %></h1>
  <p class="description"><%= t('services.rehabilitation.description') %></p>
  <%= render 'shared/carousel', location: 'carousel/services/rehabilitation', n_items: 6 %>
  <%= link_to(contact_path, class: 'info-button') do %>
    <%= t('btn.ask-info') %>
  <% end %>
</div>

app/views/pages/trajectory.html.erb
<%= render 'shared/carousel', location: 'carousel/trajectory', n_items: 5 %>

<div class="container trajectory-page">
  <h1 class="title"><%= t('trajectory.title') %></h1>
  <p class="description"><%= t('trajectory.description_1') %></p>
  <p class="description"><%= t('trajectory.description_2') %></p>
  <p class="description"><%= t('trajectory.description_3') %></p>

  <%= image_tag("premis_alejandro_de_la_sota.png", alt: "", class: "award") %>
</div>

app/views/shared/_carousel.html.erb
<% id = "carousel#{location.split('/').last.capitalize}" %>
<div id="<%= id %>" class="carousel slide" data-bs-ride="carousel">
  <div class="carousel-inner">
    <% n_items.times do |i| %>
      <div class="carousel-item <%= 'active' if i == 0 %>">
        <%= image_tag("#{location}/desktop/#{i+1}.png", class: "carousel-image d-none d-sm-block") %>
        <%= image_tag("#{location}/mobile/#{i+1}.png", class: "carousel-image d-sm-none") %>
      </div>
    <% end %>
  </div>
  <button class="carousel-control-prev" type="button" data-bs-target="#<%= id %>" data-bs-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Previous</span>
  </button>
  <button class="carousel-control-next" type="button" data-bs-target="#<%= id %>" data-bs-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Next</span>
  </button>
</div>

app/views/shared/_contact_data.html.erb
<div class="row row-contact-info text-center">
  <div class="col-sm-12 col-md-6 ">
    <a href="mailto:construbaixcamp@gmail.com" class="d-flex align-items-center justify-content-center">
      <%= image_tag("mail#{'-white' if white_logos}.svg", class: 'icon') %>
      <span>construbaixcamp@gmail.com</span>
    </a>
  </div>
  <div class="col-sm-12 col-md-6 mt-3 mt-md-0">
    <a href="tel:+34606417415" class="d-flex align-items-center justify-content-center">
      <%= image_tag("call#{'-white' if white_logos}.svg", class: 'icon') %>
      <span>606 417 415</span>
    </a>
  </div>
</div>